### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by matthewp** [matthewp/stream-when#1]
```
Step 2: Run donejs init
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:179:15)
    at Socket.Readable.on (_stream_readable.js:671:33)
    at /Users/matthew/Projects/donejs/node_modules/stream-when/stream-when.js:11:12
    at streamWhen (/Users/matthew/Projects/donejs/node_modules/stream-when/stream-when.js:10:10)
    at /Users/matthew/Projects/donejs/node_modules/guide-automation/node_modules/answer-prompt/answer-prompt.js:7:12
    at Object.fn (/Users/matthew/Projects/donejs/guides/guide/test.js:37:2)
    at /Users/matthew/Projects/donejs/node_modules/guide-automation/lib/guide-test.js:174:42
    at oneAtATime (/Users/matthew/Projects/donejs/node_modules/guide-automation/node_modules/promise-one-at-a-time/one.js:13:10)
    at /Users/matthew/Projects/donejs/node_modules/guide-automation/node_modules/promise-one-at-a-time/one.js:15:9
    at runMicrotasksCallback (node.js:337:7)
```

**Comment by matthewp** [comment]
Fixed by https://github.com/matthewp/answer-prompt/pull/1
